// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqnfoxdfvbcfgjfjpyxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbmZveGRmdmJjZmdqZmpweXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzM2NDksImV4cCI6MjA2NjkwOTY0OX0.UJPSeZOWBgiIppMzu0_pObq3kx-U6vGgnt0XiGhnKdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});